//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int id { get; set; }
        public string orderid { get; set; }
        public string batchno { get; set; }
        public string amount { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> submittime { get; set; }
        public string batchContent { get; set; }
        public Nullable<int> uid { get; set; }
        public string orderstatus { get; set; }
        public string remark { get; set; }
        public string iseable { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string createBank { get; set; }
        public string branchBank { get; set; }
        public string branchBankZH { get; set; }
        public string bankNumber { get; set; }
        public string belongTo { get; set; }
        public string api { get; set; }
        public string userName { get; set; }
        public string loginId { get; set; }
        public string inputPerson { get; set; }
    }
}
