//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string userPhone { get; set; }
        public string userPwd { get; set; }
        public string remark { get; set; }
        public Nullable<int> roleId { get; set; }
        public string loginId { get; set; }
        public string createBank { get; set; }
        public string branchBank { get; set; }
        public string branchBankZH { get; set; }
        public string bankNumber { get; set; }
        public string belongTo { get; set; }
        public string createtime { get; set; }
        public string updatetime { get; set; }
        public string iseable { get; set; }
        public string api { get; set; }
        public string isUpdatePass { get; set; }
        public string inputPerson { get; set; }
        public string province { get; set; }
        public string city { get; set; }
    }
}
